[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
port = 1420
open = false

[tools]
tailwindcss = "2.7.0" # This is actually the version of tailwindcss-extra
# tailwindcss-extra = "2.7.0"
